apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-external-contractor
  namespace: team2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-external-contractor
  namespace: team2
rules:
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-external-contractor
  namespace: team2
subjects:
- kind: ServiceAccount
  name: sa-external-contractor
  namespace: team2
roleRef:
  kind: Role
  name: role-external-contractor
  apiGroup: rbac.authorization.k8s.io

